### ISSUE TITLE
Actions Features

### ISSUE THREAD

**Issue by kitsonk** [dojo/actions#3]
In doing the initial prototype, here are a few things that I thought of that we should consider for actions:
- `do()` returns a promise with `redo()` and `undo()`.  It is up the method implementor to figure out what it actually needs to do to _undo_ something.  A potential improvement is that the `action.state` is cloned after `.do()` and passed into `undo()`/`redo()`.  This way if you fire off a bunch of `.do()` you don't have to worry about how many you have in flight.  Another way of managing this is that whatever is returned/resolved from the `do()` (or previous method in the chain) is passed into `undo()`/`redo()`. (Actually writing that down, I liked the second option)
- When no `undo()` method is specified upon instantiation, it results in a noop, which is resolved with no value.  Maybe it makes sense to resolve with the previous value in the chain.
- Not sure what the best behaviour is for rejection/throws in a long chain.  I realised I didn't actually code a behaviour, but I don't know if a long chain of `.do().undo().redo()` if each subsequent method should just reject with the previous value.
- Post instantiation, there is no designed way to replace the `do()`/`undo()`/`redo()` implementation methods.  Don't know if that is desired/logical.
- There is no way of customising the returned promise further.  Again, I don't know if this just adds arbitrary complexity.
- It isn't based on Evented. Therefore there are no built in event mechanisms.  Again, I don't know if this is logical/expected.
- At run-time, calling `do()`, `undo()`, or `redo()` with different arity of arguments then specified in the interface does not pass these onto the implementation method.  This is sort of "mean" in the sense that if you decided you want to pass something to `undo()`, your method won't receive it.  Conceptually it would be anti-pattern to supply arguments to `undo()` but is it fair to actually discard them?

**Comment by msssk** [comment]
1. For implementors to be able to implement `undo()` they are generally going to need to know precisely what `do()` did, which means knowing the state prior to the execution of `do()` and the state immediately after the execution of `do()`. Right now `state` only exists on the action factory; no state history is maintained by the trail of actions. Passing the result of `do()` to `undo()` does not address this - `undo()` still doesn't have the information it needs to be able to undo whatever `do()` did. So I think we may need to clone `state` _before_ executing `do()` and store it on the action. And then pass the result of `do()` to `undo()`.
2. Yeah, I think to keep the chain valid noops should probably return the result of the most recent successful op.
3. I think a rejection or error should cancel the rest of the chain.
4. I think we'll have to put actions into practice to see. It does look like destroying an action will currently enable you to redefine it.
5. No opinion on customizing returned promise.
6. Can't think of why it would need `Evented`.
7. Abide by the method signature or suffer the consequences!

**Comment by msssk** [comment]
I'm not quite sure how `redo()` should work, but it might not make sense to have it default to `do()` when undefined. I would think like `undo()`, `redo()` would take no parameters. I think it would be clearer in client code to simply re-execute `do()` (along with the relevant parameters) than to call `redo()` to achieve the same effect.

`redo()` should only be executable when `undo()` has been called.

**Comment by msssk** [comment]
It seems like we might not want to [decorate errors](https://github.com/dojo/actions/blob/84d175fac58444b1ad66126319940252502bae32/src/actions.ts#L201). Or decorate them in a way that `undo()` and `redo()` simply propagate the error.

**Comment by gbaumgart** [comment]
no idea what the purpose is of this class, and no offense but: i tried this model and it didn't work out well for me, especially on the performance side. Consider a few grid instances, having each around 100 actions easily (60% are standard grid actions) and each of those can have an own internal version of its own per visibility, containing a state for label, enabled, icon, widget-class, widget options but also optional processing options (action value from/to its reference) . Thats usually around 3-5+ of them: context menu, local toolbar, global toolbar, main - menu, and property views,...). Of course not all need that but rich actions like sort, group, option toggles do indeed need an override for these widgets.

And, there isn't only do/undo/redo btw., I had to introduce 'preview' as well (do/undo isn't really an option).  I optimized this with dstore backed ring buffer cache which avoids re-creation of the action class(usually also a dmodel object). 

However, I am amazed where this goes, working on a good and flexible, and re-usable 'Action' class turned out as bigger project that thought over the years, keeps me busy almost every day.
just saying, have fun

**Comment by kitsonk** [comment]
> no idea what the purpose is of this class, and no offense but: i tried this model and it didn't work out well for me, especially on the performance side.

To be honest, it seems like you do, because you expound up the reasons why it doesn't work... so I assume you understand what it is for.

Actions are a [part](https://facebook.github.io/flux/docs/overview.html) of several modern frameworks and are a [common](http://www.joezimjs.com/javascript/javascript-design-patterns-command/) [pattern](http://www.dofactory.com/javascript/command-design-pattern) [in](https://developer.s24.com/blog/js-command-pattern-for-undo-and-redo.html) [JavaScript](http://www.digiguru.co.uk/blog/2015/03/19/the-command-pattern-an-example-in-javascript.html).

Thanks for your thoughts on where you struggled with something similar though...  Avoiding many of those issues will be a consideration.

**Comment by gbaumgart** [comment]
Thanks for the links, very interesting!  Btw. and just to round this up: you actually need at least 3 classes for user-actions:

1. Action. Btw. Instead of the type property, its 'command' (dmodel collides here). I am using this property for the action - store id but also to extract the label from the last command segment (Clipboard/Copy). I also use it to build menu trees, using the overrides to restructure the rendering.

2. ActionProvider. A mixin and interface: createAction, runAction(action,args), onBeforeAction, onAfterAction(restores usually focus and a new or old selection). This is applied to grids and will be the default owner of the action created. You actually also have multiple Action-Stores here. A local, and sometimes global (plugins) action - stores.

3. ActionConsumer. A mixin for Action-Renderers like Context-Menu, Ribbons, Main-Menu. It will use the local property 'visibility' to find overrides for each action when rendered. This class also should support multiple ActionProviders. (Main-Menu for instance). This interface has setProvider, addProvider, removeProvider.

'do' is btw. implemented most of the time by the owner, not the action itself.

After all you want this:
- grid.runAction(action|commandString,args|null). Most of the time this will be applied to the current selection
- grid.setActionProperty(action|command-string,key,value). For instance: setActionProperty('Clipboard/Paste','disabled',true) should update all referencing widgets (MenuItem, Toolbar-Button,...) and disable this action visually. 
- Create compound actions out of existing actions, as you did for Maqetta. 
- Highlight actions visually (wizards, intro tours). 
- Having easier unit-tests and create a sort of macro system to compose new actions more easy.

ok, just wanted to add my 2 cents (after fighting with Maqetta for years on this ;-)

**Comment by gbaumgart** [comment]
[This,one of my mess](https://gitlab.com/xamiro/xcf-dist-windows/uploads/6f8083d15b80277eaa0f182670ffcfd9/image.png) pretty much illustrates the problem. All versions of an action are linked to a another target widget with different mappings per binding. They beaty I figured was that most actions could be displayed with a grid, its all there already.

**Comment by kitsonk** [comment]
Closing for now... we have revised Actions for the time being to simplify them and may revisit features in the future.
